### ISSUE TITLE
new and unique

### ISSUE THREAD

**Issue by torkus** [WoWAddonManager/wam-client#3]
hi, this is a pretty unique approach to addon management. Do you think you could elaborate on your motivations in the README? Maybe add a screenshot of the GUI?

I'd like to add you to [my list](https://ogri-la.github.io/wow-addon-managers/).

**Comment by jorbo** [comment]
Thanks for taking such an early interest in this project! I'll add the things you suggested to the README.  
  
You're welcome to add this project to your list, but fair disclaimer the client is still in very early in development and so barely any of the major features are even implemented so its unusable as actual addon manager.

**Comment by torkus** [comment]
Fair enough, I'll hold off for now. 

There have been a few grumblings about centralised addon hosts and a few addon managers support git and github as a means to get away from the behemoths (as well as keeping on the bleeding edge of an addon).

I'll keep an eye on things for now. Welcome to the neighbourhood :P
